<a href="https://colab.research.google.com/github/beyounding/dyslexia_projects/blob/main/dyscalculia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Theoretical foundations

> Cohen Kadosh, R., Dowker, A., Heine, A., Kaufmann, L., & Kucian, K. (2013). Interventions for improving numerical abilities: Present and future. Trends in Neuroscience and Education, 2(2), 85–93. doi:10.1016/j.tine.2013.04.001

Children in the project receive interventions from trained teachers or teaching assistants during two 15 min sessions per week, typically for one school term.

The components are as follows:

(1) Counting verbally (counting verbally from 0 or 1; counting on from a given number; counting back from a given number).

(2) Counting objects (counting objects; order irrelevance; repeated addition of objects; repeated subtraction of objects).

(3) Reading and writing numerals and number words.

(4) Handling tens and units (number comparison; adding tens and units; subtracting tens and units).

(5) Ordinal numbers (stating the ordinal position – e.g. second, fourth, etc – of a bead within a bead string).

(6) Word problems.

(7) Translation between different formats (i.e. between quantities of objects and number words or numerals).

(8) Derived fact strategies (including the use of commutativity of addition and the inversion principle for addition and subtraction to derive unknown number facts from a given number fact).

(9) Estimation of set size, and of answers to arithmetic problems.

(10) Remembered number facts.

In [ ]:
import pandas as pd
import numpy as np
import random
from random import randint
from itertools import permutations

In [ ]:
df = pd.read_csv('/content/database.csv')

In [ ]:
df.head()

  Participants    A1   A2   A3   A4   A5   A6   A7
0            P1  0.5  0.7  0.4  0.8  0.9  0.8  0.8
1            P2  0.8  0.5  0.4  0.4  0.4  0.3  0.9
2            P3  0.7  0.5  0.8  0.3  0.9  0.5  0.3
3            P4  0.8  0.4  0.5  0.2  0.3  0.2  0.8
4            P5  0.5  0.3  0.2  0.4  0.5  0.8  0.4

In [ ]:
df.iloc[1:2, 1:]

    A1   A2   A3   A4   A5   A6   A7
1  0.8  0.5  0.4  0.4  0.4  0.3  0.9

In [ ]:
intervention_path=[]

for name, values in df.iloc[1:2, 1:].iteritems():
    if float(values) < float(0.5) or float(values) == float(0.5):
      intervention_path.append(str(name))

intervention_path

['A2', 'A3', 'A4', 'A5', 'A6']

**A1**	Remembered number facts 	
**A2**	Derived fact strategies (computing arithmetic exercises)	
**A3**	Estimation of set size, and of answers to arithmetic problems
**A4**	Comprehending algorithms of addition, subtraction, multiplication, and division	
**A5**	Derived fact strategies	(the use of commutativity of addition and the inversion principle for addition and subtraction)

**A6**	Misplacing digits	
**A7**	Number perception

**Training generation**

---

In [ ]:
for i in intervention_path:

  if i=='A2' or i=='A4' or i=='A1':
    ch=0
    while ch<3:
      arithmetic_signs = ['*', '/', '-', '+']
      ar = random.choice(arithmetic_signs)
      a = randint(0, 9)
      b = randint(0, 9)
      exercise=str(a)+str(ar)+str(b)+'='+'?'
      print(*exercise)
      ch+=1
    print('')

  if i =='A5' or i=='A1':
    ch=0
    while ch<3:
      exercises = ['(operand1-operand2)*operand1', '(operand1-operand2)*operand2', '(operand1+operand2)*operand1', '(operand1+operand2)*operand2']
      ar = random.choice(exercises)
      a = randint(0, 9)
      b = randint(0, 9)
      print(random.choice(exercises))
      print('operand 1 = '+str(a))
      print('operand 2 = '+str(b))
      print(' ')
      ch+=1
    print('')

  if i=='A3' or i=='A1':
     ch=0
     while ch<3:
       a = randint(0, 9)
       b = randint(0, 9)
       exercise=str(a)+'*'+str(b)+'='+'?'
       print(*exercise)
       ch+=1
     print('')

  if i=='A6' or i=='A1':
     ch=0
     while ch<3:
       a = randint(100, 999)
       a=str(a)
       b=[a[2]+a[0]+a[1], a[1]+a[2]+a[0], a[1]+a[0]+a[2], a[2]+a[1]+a[0], a[0]+a[1]+a[2], a[0]+a[2]+a[1]]
       a2=random.choice(b)
       print(str(a)+'='+str(a2)+'?')
       
       ch+=1
     print('')

  if i=='A7' or i=='A1':
     ch=0
     while ch<3:
       zeros = randint(1, 10)
       a=[1]+[0]*zeros
       print(*a)
        
       ch+=1
     print('')

1 / 0 = ?
7 * 9 = ?
5 + 1 = ?

2 * 9 = ?
1 * 5 = ?
4 * 5 = ?

2 / 0 = ?
8 + 5 = ?
2 / 0 = ?

(operand1-operand2)*operand2
operand 1 = 9
operand 2 = 9

(operand1-operand2)*operand1
operand 1 = 0
operand 2 = 8

(operand1-operand2)*operand1
operand 1 = 9
operand 2 = 1


618=816?
637=763?
386=836?